### ISSUE TITLE
Doesn't install via pip or pip3

### ISSUE THREAD

**Issue by parthe** [stephane-caron/lpsolvers#1]
$ pip install lpsolvers
Collecting lpsolvers
  Using cached https://files.pythonhosted.org/packages/6d/88/7134bcbf55e06b80d3a147b55760e0467d46f30bb66786c67ab1fe79f3ca/lpsolvers-0.8.8.tar.gz
Collecting cvxopt (from lpsolvers)
  Using cached https://files.pythonhosted.org/packages/b8/d7/14dee48a26af514e03d2f00347b2b79e5ae558dc8497e5f64cfa847a988f/cvxopt-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycddlib (from lpsolvers)
  Using cached https://files.pythonhosted.org/packages/1c/e7/ba71780e10fd9787cd7f1e05ce81859433b5c8e9abb135b4039202878ac1/pycddlib-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-42YLj7/pycddlib/setup.py", line 49, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-42YLj7/pycddlib/

**Comment by stephane-caron** [comment]
Hmm, that's an error from the [pycddlib](https://github.com/mcmtroffaes/pycddlib) dependency. It says you don't have Cython installed on your system.

Try installing Cython by, e.g. on Ubuntu/Debian:
```
sudo apt-get install python-dev build-essential
sudo pip install cython
```
Then ``pip install lpsolvers`` again.

**Comment by parthe** [comment]
That worked!
