### ISSUE TITLE
Error in Readme (command seems to solve minimization not maximization)

### ISSUE THREAD

**Issue by parthe** [stephane-caron/lpsolvers#3]
I think the command solve_lp(c,G,h) solves the program

min c.T x : Gx <= h

(not max) as against what is currently mentioned in the documentation.

Check by running the following program (attaching the polytope for reference)
Attaching ref to cvxopt cone solver page (http://cvxopt.org/userguide/coneprog.html#linear-cone-programs)

c = array([1,1.])
G = array([[0, -1.],[-1., 0],[1,2],[2,1]])
h = array([0.,0,3,3])
print(solve_lp(c,G,h))

c = array([-1,-1.])
G = array([[0, -1.],[-1., 0],[1,2],[2,1]])
h = array([0.,0,3,3])
print(solve_lp(c,G,h))

![image](https://user-images.githubusercontent.com/5085600/47328959-d7f49880-d627-11e8-9382-cce2aff06eb0.png)

**Comment by stephane-caron** [comment]
It is indeed a ``min``, not a ``max``. Thanks for spotting this typo! I just fixed it.
