### ISSUE TITLE
Version of lpsolve() on which 'lpsolvers' is based ?

### ISSUE THREAD

**Issue by Cbhihe** [stephane-caron/lpsolvers#7]
Hi,
Thank you for making this port available. 
I saw no mention of and would be interested in knowing:
 - the version of lpsolve() en la que se basa `lpsolvers' ?  Is it v5.5.2.5 ?
 - the latest Python version with which your package is compatible ? (if relevant)
 
 Thank you.

**Comment by stephane-caron** [comment]
Sure:

> the version of lpsolve() en la que se basa `lpsolvers' ? Is it v5.5.2.5 ?

This package is an independent development, not a port of an existing function from another language.

> the latest Python version with which your package is compatible ? (if relevant)

This information is displayed on [the PyPI page of lpsolvers](https://pypi.org/project/lpsolvers/). You can also find it in the projet's [`pyproject.toml`](https://github.com/stephane-caron/lpsolvers/blob/main/pyproject.toml) file.

**Comment by stephane-caron** [comment]
Closing as this should answer your question; feel free to re-open otherwise.

**Comment by Cbhihe** [comment]
I should have looked better before dropping you a note. Sorry for the noise. Thank you.
